modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "shrink"
version = "${version}"
displayName = "Shrink"
authors = "Gigabit101"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.shrink]]
modId = "neoforge"
type="required" #mandatory
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.shrink]]
modId = "minecraft"
type="required" #mandatory
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.shrink]]
modId = "architectury"
type="required" #mandatory
versionRange = "[13.0.1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.shrink]]
modId = "polylib"
type="required" #mandatory
versionRange = "[2100.0.3,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "shrink.mixins.json"
