name: Java CI with Gradle

on:
  push:
    branches: [ 1.20.2/dev ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      env:
        CURSE_API_KEY: ${{ secrets.CURSE_API_KEY }}

      run: |
        chmod +x ./gradlew
        ./gradlew build --stacktrace --no-daemon
    - name: Release to Maven and CurseForge
      uses: gradle/gradle-build-action@v2
      if: |
        !contains(github.event.head_commit.message, '[norelease]') && github.event.inputs.norelease != 'true'
      env:
        # currently unused, may want to use these for changelogs though!
        # GIT_COMMIT: ${{ github.event.after }}
        # GIT_PREVIOUS_COMMIT: ${{ github.event.before }}
        MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
        CURSE_API_KEY: ${{ secrets.CURSE_API_KEY }}
        MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
      with:
        arguments: publish publishUnified --stacktrace --no-daemon
