name: Java CI with Gradle

on:
  push:
    branches: [ arch/1.21 ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Build with Gradle
      env:
        CURSE_API_KEY: ${{ secrets.CURSE_API_KEY }}
      run: |
        chmod +x ./gradlew
        ./gradlew build publish publishUnified --stacktrace --no-daemon
